apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service # Name of the Service
spec:
  # Select pods with the label app=go-web-app
  selector:
    app: go-web-app
  ports:
    - protocol: TCP # Protocol used by the Service
      port: 80 # Service port exposed to clients
      targetPort: 8080 # Port on the pod to forward traffic to
  type: ClusterIP # Internal service type, reachable only within the cluster     
